### ISSUE TITLE
getWebsite on yahooWeather plugin

### ISSUE THREAD

**Issue by themrzmaster** [janrueth/SiriServerPlugins#10]
hey, every time a make a request, siri saty loading and i have the error on terminal:

ERROR Unexpected error during plugin processing
Traceback (most recent call last):
  File "/home/zmaster/SiriServerCore/plugin.py", line 101, in run
    self.**method(self, self.__speech, self.__lang)
  File "/home/zmaster/SiriServerCore/plugins/yahooWeather/__init**.py", line 623, in forcastWeatherAtCurrentLocation
    result = getWebsite(reverseLookup, timeout=5)
NameError: global name 'getWebsite' is not defined

what is it?

thx

**Comment by 0xSekar** [comment]
Hello,

Replace The call to getWebsite to self.getWebsite
