### ISSUE TITLE
timestamp out of range for platform time_t - shortMessage

### ISSUE THREAD

**Issue by ids-dev** [janrueth/SiriServerPlugins#8]
please find attached a log of what happens when i request to send a sms to contacts 

root@core:~/core# python SiriServer.py --port 443
INFO Starting server on port 443
INFO Loading Session Certificates
INFO Setting Up Database
INFO Connection to Database
INFO Loading Plugin Framework
INFO Server is running and listening for connections
INFO New connection from 94.6.231.234 on port 49554
INFO Currently 1 clients connected
INFO Sending flac to google for recognition
INFO Best matching result: "Send a message to wifey" with a confidence of 89.79%
WARNING This class is deprecated use the AB version instead
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 37, in callWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/epollreactor.py", line 217, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 137, in doRead
    return Connection.doRead(self)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 460, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.6/dist-packages/twisted/protocols/basic.py", line 259, in dataReceived
    return self.rawDataReceived(data)
  File "/root/core/SiriCore.py", line 121, in rawDataReceived
    self.process_compressed_data()
  File "/root/core/SiriCore.py", line 131, in process_compressed_data
    plist = biplist.readPlistFromString(obj.plist)
  File "/root/core/biplist/__init__.py", line 117, in readPlistFromString
    return readPlist(StringIO(data))
  File "/root/core/biplist/**init**.py", line 91, in readPlist
    result = reader.parse()
  File "/root/core/biplist/**init**.py", line 152, in parse
    return self.readRoot()
  File "/root/core/biplist/**init**.py", line 184, in readRoot
    result = self.readObject()
  File "/root/core/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/root/core/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/root/core/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/root/core/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/root/core/biplist/**init**.py", line 247, in readObject
    result = self.readArray(extra)
  File "/root/core/biplist/**init**.py", line 297, in readArray
    value = self.readObject()
  File "/root/core/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/root/core/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/root/core/biplist/**init**.py", line 255, in readObject
    result = self.readDict(extra)
  File "/root/core/biplist/**init**.py", line 311, in readDict
    value = self.readObject()
  File "/root/core/biplist/**init**.py", line 228, in readObject
    result = self.readDate()
  File "/root/core/biplist/**init**.py", line 331, in readDate
    result = datetime.datetime.utcfromtimestamp(result + apple_reference_date_offset)
exceptions.ValueError: timestamp out of range for platform time_t
ERROR Connection Lost: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: timestamp out of range for platform time_t
]
INFO Currently 0 clients connected

please could you advise me

thanks

**Comment by janrueth** [comment]
The contact has a malformed date (no year or so), unfortunately the biplist library does not fetch that. This will cause that error on 32bit machines

**Comment by ids-dev** [comment]
thanks, perfect fix :)
